/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package uva.ipc.libreria.vista;


import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import uva.ipc.libreria.modelo.Libro;

/**
 * Esta es la clase vista Busqueda de la aplicación.
 * @author juagonz0
 * @author alemina
 */
public class VistaBusqueda extends javax.swing.JFrame {
    
    private final ControladorBusqueda controlador;
    
    /**
     * Constructor de la vista. Se encarga de conectar la vista al controlador Busqueda.
     */
    public VistaBusqueda() {
        initComponents();
        controlador = new ControladorBusqueda(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jButtonMenuInicial = new javax.swing.JButton();
        jButtonInsercion = new javax.swing.JButton();
        jButtonGuardar = new javax.swing.JButton();
        jButtonAbrir = new javax.swing.JButton();
        jCheckBoxMantenerLIsta = new javax.swing.JCheckBox();
        jPanel11 = new javax.swing.JPanel();
        jLabelFiltro = new javax.swing.JLabel();
        jComboBoxFiltro = new javax.swing.JComboBox<>();
        jTextFieldFiltro = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableLibros = new javax.swing.JTable();
        jLabelMensaje = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabelTitulo = new javax.swing.JLabel();
        jLabelDescr = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaDescr = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jLabelISBN = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabelEstado = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabelPrecio = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabelLeido = new javax.swing.JLabel();
        jButtonEditarLibro = new javax.swing.JButton();
        jPanel13 = new javax.swing.JPanel();
        jLabelInformacion = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Biblioteca | Búsqueda");
        setMinimumSize(new java.awt.Dimension(850, 650));
        setPreferredSize(new java.awt.Dimension(850, 650));

        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jButtonMenuInicial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uva/ipc/libreria/vista/imagenes/Gnome-go-home.png"))); // NOI18N
        jButtonMenuInicial.setToolTipText("Menu Inicial");
        jButtonMenuInicial.setFocusable(false);
        jButtonMenuInicial.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonMenuInicial.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonMenuInicial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMenuInicialActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonMenuInicial);

        jButtonInsercion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uva/ipc/libreria/vista/imagenes/libro.png"))); // NOI18N
        jButtonInsercion.setToolTipText("Edición Manual");
        jButtonInsercion.setFocusable(false);
        jButtonInsercion.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonInsercion.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonInsercion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInsercionActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonInsercion);

        jButtonGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uva/ipc/libreria/vista/imagenes/Gnome-media-floppy.png"))); // NOI18N
        jButtonGuardar.setToolTipText("Guardar");
        jButtonGuardar.setFocusable(false);
        jButtonGuardar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonGuardar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonGuardar);

        jButtonAbrir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uva/ipc/libreria/vista/imagenes/Gnome-document-open.png"))); // NOI18N
        jButtonAbrir.setToolTipText("Abrir");
        jButtonAbrir.setFocusable(false);
        jButtonAbrir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonAbrir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAbrirActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonAbrir);

        jCheckBoxMantenerLIsta.setText("Mantener la lista");
        jCheckBoxMantenerLIsta.setFocusable(false);
        jPanel1.add(jCheckBoxMantenerLIsta);
        jPanel1.add(jPanel11);

        jLabelFiltro.setText("Filtrar por");
        jLabelFiltro.setFocusable(false);
        jPanel1.add(jLabelFiltro);

        jComboBoxFiltro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Título", "ISBN" }));
        jComboBoxFiltro.setFocusable(false);
        jComboBoxFiltro.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxFiltroItemStateChanged(evt);
            }
        });
        jPanel1.add(jComboBoxFiltro);

        jTextFieldFiltro.setColumns(13);
        jTextFieldFiltro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldFiltroKeyReleased(evt);
            }
        });
        jPanel1.add(jTextFieldFiltro);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jTableLibros.setAutoCreateRowSorter(true);
        jTableLibros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Título", "Precio", "ISBN"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableLibros.setFillsViewportHeight(true);
        jTableLibros.setMinimumSize(new java.awt.Dimension(0, 0));
        jTableLibros.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTableLibros.setShowVerticalLines(true);
        jTableLibros.getTableHeader().setReorderingAllowed(false);
        jTableLibros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableLibrosMouseClicked(evt);
            }
        });
        jTableLibros.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTableLibrosKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTableLibros);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jLabelMensaje.setText("Busque aplicando filtros, abra ficheros, edite libros...");
        getContentPane().add(jLabelMensaje, java.awt.BorderLayout.PAGE_END);

        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel3.setLayout(new java.awt.BorderLayout());
        jPanel3.add(jPanel4, java.awt.BorderLayout.PAGE_START);
        jPanel3.add(jPanel5, java.awt.BorderLayout.LINE_END);
        jPanel3.add(jPanel6, java.awt.BorderLayout.LINE_START);
        jPanel3.add(jPanel7, java.awt.BorderLayout.SOUTH);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uva/ipc/libreria/vista/imagenes/biblioteca.png"))); // NOI18N
        jPanel9.add(jLabel7);

        jPanel3.add(jPanel9, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel3, java.awt.BorderLayout.SOUTH);

        jPanel8.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Título:");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel1.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        jPanel8.add(jLabel1, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        jPanel8.add(jLabelTitulo, gridBagConstraints);

        jLabelDescr.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelDescr.setText("Descripción:");
        jLabelDescr.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabelDescr.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        jPanel8.add(jLabelDescr, gridBagConstraints);

        jTextAreaDescr.setColumns(20);
        jTextAreaDescr.setLineWrap(true);
        jTextAreaDescr.setRows(5);
        jTextAreaDescr.setDisabledTextColor(new java.awt.Color(60, 63, 65));
        jTextAreaDescr.setEnabled(false);
        jTextAreaDescr.setFocusable(false);
        jScrollPane2.setViewportView(jTextAreaDescr);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel8.add(jScrollPane2, gridBagConstraints);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("ISBN:");
        jLabel3.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel3.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        jPanel8.add(jLabel3, gridBagConstraints);

        jLabelISBN.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabelISBN.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        jPanel8.add(jLabelISBN, gridBagConstraints);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Estado:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        jPanel8.add(jLabel4, gridBagConstraints);

        jLabelEstado.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabelEstado.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        jPanel8.add(jLabelEstado, gridBagConstraints);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Precio:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        jPanel8.add(jLabel2, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        jPanel8.add(jLabelPrecio, gridBagConstraints);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Leído:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        jPanel8.add(jLabel5, gridBagConstraints);

        jLabelLeido.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabelLeido.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        jPanel8.add(jLabelLeido, gridBagConstraints);

        jButtonEditarLibro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uva/ipc/libreria/vista/imagenes/Gnome-accessories-text-editor.png"))); // NOI18N
        jButtonEditarLibro.setToolTipText("Editar");
        jButtonEditarLibro.setEnabled(false);
        jButtonEditarLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarLibroActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 2;
        jPanel8.add(jButtonEditarLibro, gridBagConstraints);

        jPanel2.add(jPanel8, java.awt.BorderLayout.CENTER);
        jPanel8.getAccessibleContext().setAccessibleParent(this);

        jLabelInformacion.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabelInformacion.setText("Información del Libro");
        jPanel13.add(jLabelInformacion);

        jPanel2.add(jPanel13, java.awt.BorderLayout.PAGE_START);
        jPanel2.add(jPanel15, java.awt.BorderLayout.WEST);
        jPanel2.add(jPanel16, java.awt.BorderLayout.EAST);

        getContentPane().add(jPanel2, java.awt.BorderLayout.EAST);
        getContentPane().add(jPanel10, java.awt.BorderLayout.LINE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonMenuInicialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMenuInicialActionPerformed
        controlador.procesaEventoMenuInicial();
    }//GEN-LAST:event_jButtonMenuInicialActionPerformed

    private void jButtonInsercionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInsercionActionPerformed
        controlador.procesaEventoInsercion();
    }//GEN-LAST:event_jButtonInsercionActionPerformed

    private void jButtonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarActionPerformed
        controlador.procesaEventoGuardar();
    }//GEN-LAST:event_jButtonGuardarActionPerformed

    private void jButtonAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAbrirActionPerformed
        controlador.procesaEventoAbrir();
    }//GEN-LAST:event_jButtonAbrirActionPerformed

    private void jButtonEditarLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarLibroActionPerformed
        controlador.procesaEventoEditarLibro();
    }//GEN-LAST:event_jButtonEditarLibroActionPerformed

    private void jTableLibrosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableLibrosMouseClicked
        controlador.procesaEventoCargarLibro(evt.getClickCount());
    }//GEN-LAST:event_jTableLibrosMouseClicked

    private void jTextFieldFiltroKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldFiltroKeyReleased
        controlador.procesaEventoFiltro();
    }//GEN-LAST:event_jTextFieldFiltroKeyReleased

    private void jComboBoxFiltroItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxFiltroItemStateChanged
        controlador.procesaEventoFiltro();
    }//GEN-LAST:event_jComboBoxFiltroItemStateChanged

    private void jTableLibrosKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTableLibrosKeyReleased
        controlador.procesaEventoCargarLibro(1);
    }//GEN-LAST:event_jTableLibrosKeyReleased

    /**
     * Devuelve la fila de la tabla seleccionada
     * @return int con el numero de la fila seleccioanda
     */
    public int getFilaSeleccionada(){
        return jTableLibros.getSelectedRow();
    }
    
    /**
     * Permite mostrar los campos de libro en la pantalla
     * @param l libro que se quiere mostrar
     */
    public void mostrarLibro(Libro l){
        jLabelTitulo.setText(l.getTitulo());
        jTextAreaDescr.setText(l.getDescripcion());
        jLabelEstado.setText(l.getEstadoStr());
        jLabelISBN.setText(l.getIsbn());
        jLabelPrecio.setText(l.getPrecio() + "€");
        jLabelLeido.setText(l.isLeidoStr());
        jButtonEditarLibro.setEnabled(true);
    }
    
    /**
     * Permite actualizar la lista de libros de la tabla
     * @param datos ArrayList con los datos que se quieren mostrar
     */
    public void actualizarLista(ArrayList<Libro> datos){
        DefaultTableModel modelo = (DefaultTableModel) jTableLibros.getModel();
        modelo.setRowCount(0); //Borramos todas las celdas
        for (Libro libro : datos){
            String titulo = libro.getTitulo();
            String precio = Integer.toString(libro.getPrecio());
            String isbn = libro.getIsbn();
            Object[] fila = {titulo, precio, isbn};
            modelo.addRow(fila);
        }
    }
    
    /**
     * Devuelve la opcion de nombre o isbn en funcion de por cual se vaya a filtar 
     * @return int en función de que se vaya a filtrar. 0 si es nombre, 1 si es isbn
     */
    public int getColumnaFiltrada(){
        return jComboBoxFiltro.getSelectedIndex();
    }
    
    /**
     * Devuelve el texto con el que se va a filtrar
     * @return String con el texto
     */
    public String getTextoFiltro(){
        return jTextFieldFiltro.getText();
    }
    
    /**
     * Devuelve si se quiere mantener la lista o no al abrir un nuevo modelo
     * @return boolean si se mantiene o no 
     */
    public boolean getMantenerLista(){
        return jCheckBoxMantenerLIsta.isSelected();
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAbrir;
    private javax.swing.JButton jButtonEditarLibro;
    private javax.swing.JButton jButtonGuardar;
    private javax.swing.JButton jButtonInsercion;
    private javax.swing.JButton jButtonMenuInicial;
    private javax.swing.JCheckBox jCheckBoxMantenerLIsta;
    private javax.swing.JComboBox<String> jComboBoxFiltro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelDescr;
    private javax.swing.JLabel jLabelEstado;
    private javax.swing.JLabel jLabelFiltro;
    private javax.swing.JLabel jLabelISBN;
    private javax.swing.JLabel jLabelInformacion;
    private javax.swing.JLabel jLabelLeido;
    private javax.swing.JLabel jLabelMensaje;
    private javax.swing.JLabel jLabelPrecio;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableLibros;
    private javax.swing.JTextArea jTextAreaDescr;
    private javax.swing.JTextField jTextFieldFiltro;
    // End of variables declaration//GEN-END:variables


}
